# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

import geometry_msgs.msg
import sensor_msgs.msg
import std_msgs.msg

class AdmittanceControllerState:
    def __init__(
        self,
        *,
        mass: std_msgs.msg.Float64MultiArray = ...,
        damping: std_msgs.msg.Float64MultiArray = ...,
        stiffness: std_msgs.msg.Float64MultiArray = ...,
        rot_base_control: geometry_msgs.msg.Quaternion = ...,
        ref_trans_base_ft: geometry_msgs.msg.TransformStamped = ...,
        selected_axes: std_msgs.msg.Int8MultiArray = ...,
        ft_sensor_frame: std_msgs.msg.String = ...,
        admittance_position: geometry_msgs.msg.TransformStamped = ...,
        admittance_acceleration: geometry_msgs.msg.TwistStamped = ...,
        admittance_velocity: geometry_msgs.msg.TwistStamped = ...,
        wrench_base: geometry_msgs.msg.WrenchStamped = ...,
        joint_state: sensor_msgs.msg.JointState = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def mass(self) -> std_msgs.msg.Float64MultiArray: ...
    @mass.setter
    def mass(self, value: std_msgs.msg.Float64MultiArray) -> None: ...
    @property
    def damping(self) -> std_msgs.msg.Float64MultiArray: ...
    @damping.setter
    def damping(self, value: std_msgs.msg.Float64MultiArray) -> None: ...
    @property
    def stiffness(self) -> std_msgs.msg.Float64MultiArray: ...
    @stiffness.setter
    def stiffness(self, value: std_msgs.msg.Float64MultiArray) -> None: ...
    @property
    def rot_base_control(self) -> geometry_msgs.msg.Quaternion: ...
    @rot_base_control.setter
    def rot_base_control(self, value: geometry_msgs.msg.Quaternion) -> None: ...
    @property
    def ref_trans_base_ft(self) -> geometry_msgs.msg.TransformStamped: ...
    @ref_trans_base_ft.setter
    def ref_trans_base_ft(self, value: geometry_msgs.msg.TransformStamped) -> None: ...
    @property
    def selected_axes(self) -> std_msgs.msg.Int8MultiArray: ...
    @selected_axes.setter
    def selected_axes(self, value: std_msgs.msg.Int8MultiArray) -> None: ...
    @property
    def ft_sensor_frame(self) -> std_msgs.msg.String: ...
    @ft_sensor_frame.setter
    def ft_sensor_frame(self, value: std_msgs.msg.String) -> None: ...
    @property
    def admittance_position(self) -> geometry_msgs.msg.TransformStamped: ...
    @admittance_position.setter
    def admittance_position(
        self, value: geometry_msgs.msg.TransformStamped
    ) -> None: ...
    @property
    def admittance_acceleration(self) -> geometry_msgs.msg.TwistStamped: ...
    @admittance_acceleration.setter
    def admittance_acceleration(
        self, value: geometry_msgs.msg.TwistStamped
    ) -> None: ...
    @property
    def admittance_velocity(self) -> geometry_msgs.msg.TwistStamped: ...
    @admittance_velocity.setter
    def admittance_velocity(self, value: geometry_msgs.msg.TwistStamped) -> None: ...
    @property
    def wrench_base(self) -> geometry_msgs.msg.WrenchStamped: ...
    @wrench_base.setter
    def wrench_base(self, value: geometry_msgs.msg.WrenchStamped) -> None: ...
    @property
    def joint_state(self) -> sensor_msgs.msg.JointState: ...
    @joint_state.setter
    def joint_state(self, value: sensor_msgs.msg.JointState) -> None: ...
