# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

import std_msgs.msg

class JointControllerState:
    def __init__(
        self,
        *,
        header: std_msgs.msg.Header = ...,
        set_point: float = ...,
        process_value: float = ...,
        process_value_dot: float = ...,
        error: float = ...,
        time_step: float = ...,
        command: float = ...,
        p: float = ...,
        i: float = ...,
        d: float = ...,
        i_clamp: float = ...,
        antiwindup: bool = ...,
        check_fields: bool = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def header(self) -> std_msgs.msg.Header: ...
    @header.setter
    def header(self, value: std_msgs.msg.Header) -> None: ...
    @property
    def set_point(self) -> float: ...
    @set_point.setter
    def set_point(self, value: float) -> None: ...
    @property
    def process_value(self) -> float: ...
    @process_value.setter
    def process_value(self, value: float) -> None: ...
    @property
    def process_value_dot(self) -> float: ...
    @process_value_dot.setter
    def process_value_dot(self, value: float) -> None: ...
    @property
    def error(self) -> float: ...
    @error.setter
    def error(self, value: float) -> None: ...
    @property
    def time_step(self) -> float: ...
    @time_step.setter
    def time_step(self, value: float) -> None: ...
    @property
    def command(self) -> float: ...
    @command.setter
    def command(self, value: float) -> None: ...
    @property
    def p(self) -> float: ...
    @p.setter
    def p(self, value: float) -> None: ...
    @property
    def i(self) -> float: ...
    @i.setter
    def i(self, value: float) -> None: ...
    @property
    def d(self) -> float: ...
    @d.setter
    def d(self, value: float) -> None: ...
    @property
    def i_clamp(self) -> float: ...
    @i_clamp.setter
    def i_clamp(self, value: float) -> None: ...
    @property
    def antiwindup(self) -> bool: ...
    @antiwindup.setter
    def antiwindup(self, value: bool) -> None: ...
