# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

import builtin_interfaces.msg
import std_msgs.msg

class PidState:
    def __init__(
        self,
        *,
        header: std_msgs.msg.Header = ...,
        timestep: builtin_interfaces.msg.Duration = ...,
        error: float = ...,
        error_dot: float = ...,
        i_term: float = ...,
        p_gain: float = ...,
        i_gain: float = ...,
        d_gain: float = ...,
        output: float = ...,
        check_fields: bool = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def header(self) -> std_msgs.msg.Header: ...
    @header.setter
    def header(self, value: std_msgs.msg.Header) -> None: ...
    @property
    def timestep(self) -> builtin_interfaces.msg.Duration: ...
    @timestep.setter
    def timestep(self, value: builtin_interfaces.msg.Duration) -> None: ...
    @property
    def error(self) -> float: ...
    @error.setter
    def error(self, value: float) -> None: ...
    @property
    def error_dot(self) -> float: ...
    @error_dot.setter
    def error_dot(self, value: float) -> None: ...
    @property
    def i_term(self) -> float: ...
    @i_term.setter
    def i_term(self, value: float) -> None: ...
    @property
    def p_gain(self) -> float: ...
    @p_gain.setter
    def p_gain(self, value: float) -> None: ...
    @property
    def i_gain(self) -> float: ...
    @i_gain.setter
    def i_gain(self, value: float) -> None: ...
    @property
    def d_gain(self) -> float: ...
    @d_gain.setter
    def d_gain(self, value: float) -> None: ...
    @property
    def output(self) -> float: ...
    @output.setter
    def output(self, value: float) -> None: ...
