# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

class SingleDOFState:
    def __init__(
        self,
        *,
        name: str = ...,
        reference: float = ...,
        feedback: float = ...,
        feedback_dot: float = ...,
        error: float = ...,
        error_dot: float = ...,
        time_step: float = ...,
        output: float = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def reference(self) -> float: ...
    @reference.setter
    def reference(self, value: float) -> None: ...
    @property
    def feedback(self) -> float: ...
    @feedback.setter
    def feedback(self, value: float) -> None: ...
    @property
    def feedback_dot(self) -> float: ...
    @feedback_dot.setter
    def feedback_dot(self, value: float) -> None: ...
    @property
    def error(self) -> float: ...
    @error.setter
    def error(self, value: float) -> None: ...
    @property
    def error_dot(self) -> float: ...
    @error_dot.setter
    def error_dot(self, value: float) -> None: ...
    @property
    def time_step(self) -> float: ...
    @time_step.setter
    def time_step(self, value: float) -> None: ...
    @property
    def output(self) -> float: ...
    @output.setter
    def output(self, value: float) -> None: ...
