# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

import std_msgs.msg

class SteeringControllerStatus:
    def __init__(
        self,
        *,
        header: std_msgs.msg.Header = ...,
        traction_wheels_position: list[float] = ...,
        traction_wheels_velocity: list[float] = ...,
        steer_positions: list[float] = ...,
        traction_command: list[float] = ...,
        steering_angle_command: list[float] = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def header(self) -> std_msgs.msg.Header: ...
    @header.setter
    def header(self, value: std_msgs.msg.Header) -> None: ...
    @property
    def traction_wheels_position(self) -> list[float]: ...
    @traction_wheels_position.setter
    def traction_wheels_position(self, value: list[float]) -> None: ...
    @property
    def traction_wheels_velocity(self) -> list[float]: ...
    @traction_wheels_velocity.setter
    def traction_wheels_velocity(self, value: list[float]) -> None: ...
    @property
    def steer_positions(self) -> list[float]: ...
    @steer_positions.setter
    def steer_positions(self, value: list[float]) -> None: ...
    @property
    def traction_command(self) -> list[float]: ...
    @traction_command.setter
    def traction_command(self, value: list[float]) -> None: ...
    @property
    def steering_angle_command(self) -> list[float]: ...
    @steering_angle_command.setter
    def steering_angle_command(self, value: list[float]) -> None: ...
