# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

import rcl_interfaces.msg

class ParameterDescriptor:
    def __init__(
        self,
        *,
        name: str = ...,
        type: int = ...,  # noqa: A002
        description: str = ...,
        additional_constraints: str = ...,
        read_only: bool = ...,
        dynamic_typing: bool = ...,
        floating_point_range: list[rcl_interfaces.msg.FloatingPointRange] = ...,
        integer_range: list[rcl_interfaces.msg.IntegerRange] = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def type(self) -> int: ...
    @type.setter
    def type(self, value: int) -> None: ...
    @property
    def description(self) -> str: ...
    @description.setter
    def description(self, value: str) -> None: ...
    @property
    def additional_constraints(self) -> str: ...
    @additional_constraints.setter
    def additional_constraints(self, value: str) -> None: ...
    @property
    def read_only(self) -> bool: ...
    @read_only.setter
    def read_only(self, value: bool) -> None: ...
    @property
    def dynamic_typing(self) -> bool: ...
    @dynamic_typing.setter
    def dynamic_typing(self, value: bool) -> None: ...
    @property
    def floating_point_range(self) -> list[rcl_interfaces.msg.FloatingPointRange]: ...
    @floating_point_range.setter
    def floating_point_range(
        self, value: list[rcl_interfaces.msg.FloatingPointRange]
    ) -> None: ...
    @property
    def integer_range(self) -> list[rcl_interfaces.msg.IntegerRange]: ...
    @integer_range.setter
    def integer_range(self, value: list[rcl_interfaces.msg.IntegerRange]) -> None: ...
