# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

class ParameterValue:
    def __init__(
        self,
        *,
        type: int = ...,  # noqa: A002
        bool_value: bool = ...,
        integer_value: int = ...,
        double_value: float = ...,
        string_value: str = ...,
        byte_array_value: list[bytes] = ...,
        bool_array_value: list[bool] = ...,
        integer_array_value: list[int] = ...,
        double_array_value: list[float] = ...,
        string_array_value: list[str] = ...,
        check_fields: bool = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def type(self) -> int: ...
    @type.setter
    def type(self, value: int) -> None: ...
    @property
    def bool_value(self) -> bool: ...
    @bool_value.setter
    def bool_value(self, value: bool) -> None: ...
    @property
    def integer_value(self) -> int: ...
    @integer_value.setter
    def integer_value(self, value: int) -> None: ...
    @property
    def double_value(self) -> float: ...
    @double_value.setter
    def double_value(self, value: float) -> None: ...
    @property
    def string_value(self) -> str: ...
    @string_value.setter
    def string_value(self, value: str) -> None: ...
    @property
    def byte_array_value(self) -> list[bytes]: ...
    @byte_array_value.setter
    def byte_array_value(self, value: list[bytes]) -> None: ...
    @property
    def bool_array_value(self) -> list[bool]: ...
    @bool_array_value.setter
    def bool_array_value(self, value: list[bool]) -> None: ...
    @property
    def integer_array_value(self) -> list[int]: ...
    @integer_array_value.setter
    def integer_array_value(self, value: list[int]) -> None: ...
    @property
    def double_array_value(self) -> list[float]: ...
    @double_array_value.setter
    def double_array_value(self, value: list[float]) -> None: ...
    @property
    def string_array_value(self) -> list[str]: ...
    @string_array_value.setter
    def string_array_value(self, value: list[str]) -> None: ...
