# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

import rosgraph_msgs.msg

class Action:
    def __init__(
        self,
        *,
        name: str = ...,
        send_goal: rosgraph_msgs.msg.Service = ...,
        get_result: rosgraph_msgs.msg.Service = ...,
        cancel_goal: rosgraph_msgs.msg.Service = ...,
        feedback: rosgraph_msgs.msg.Topic = ...,
        status: rosgraph_msgs.msg.Topic = ...,
        check_fields: bool = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def send_goal(self) -> rosgraph_msgs.msg.Service: ...
    @send_goal.setter
    def send_goal(self, value: rosgraph_msgs.msg.Service) -> None: ...
    @property
    def get_result(self) -> rosgraph_msgs.msg.Service: ...
    @get_result.setter
    def get_result(self, value: rosgraph_msgs.msg.Service) -> None: ...
    @property
    def cancel_goal(self) -> rosgraph_msgs.msg.Service: ...
    @cancel_goal.setter
    def cancel_goal(self, value: rosgraph_msgs.msg.Service) -> None: ...
    @property
    def feedback(self) -> rosgraph_msgs.msg.Topic: ...
    @feedback.setter
    def feedback(self, value: rosgraph_msgs.msg.Topic) -> None: ...
    @property
    def status(self) -> rosgraph_msgs.msg.Topic: ...
    @status.setter
    def status(self, value: rosgraph_msgs.msg.Topic) -> None: ...
