# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

import rcl_interfaces.msg
import rosgraph_msgs.msg

class Node:
    def __init__(
        self,
        *,
        name: str = ...,
        parameters: list[rcl_interfaces.msg.ParameterDescriptor] = ...,
        parameter_values: list[rcl_interfaces.msg.ParameterValue] = ...,
        publishers: list[rosgraph_msgs.msg.Topic] = ...,
        subscriptions: list[rosgraph_msgs.msg.Topic] = ...,
        service_clients: list[rosgraph_msgs.msg.Service] = ...,
        service_servers: list[rosgraph_msgs.msg.Service] = ...,
        action_clients: list[rosgraph_msgs.msg.Action] = ...,
        action_servers: list[rosgraph_msgs.msg.Action] = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> None: ...
    @property
    def parameters(self) -> list[rcl_interfaces.msg.ParameterDescriptor]: ...
    @parameters.setter
    def parameters(
        self, value: list[rcl_interfaces.msg.ParameterDescriptor]
    ) -> None: ...
    @property
    def parameter_values(self) -> list[rcl_interfaces.msg.ParameterValue]: ...
    @parameter_values.setter
    def parameter_values(
        self, value: list[rcl_interfaces.msg.ParameterValue]
    ) -> None: ...
    @property
    def publishers(self) -> list[rosgraph_msgs.msg.Topic]: ...
    @publishers.setter
    def publishers(self, value: list[rosgraph_msgs.msg.Topic]) -> None: ...
    @property
    def subscriptions(self) -> list[rosgraph_msgs.msg.Topic]: ...
    @subscriptions.setter
    def subscriptions(self, value: list[rosgraph_msgs.msg.Topic]) -> None: ...
    @property
    def service_clients(self) -> list[rosgraph_msgs.msg.Service]: ...
    @service_clients.setter
    def service_clients(self, value: list[rosgraph_msgs.msg.Service]) -> None: ...
    @property
    def service_servers(self) -> list[rosgraph_msgs.msg.Service]: ...
    @service_servers.setter
    def service_servers(self, value: list[rosgraph_msgs.msg.Service]) -> None: ...
    @property
    def action_clients(self) -> list[rosgraph_msgs.msg.Action]: ...
    @action_clients.setter
    def action_clients(self, value: list[rosgraph_msgs.msg.Action]) -> None: ...
    @property
    def action_servers(self) -> list[rosgraph_msgs.msg.Action]: ...
    @action_servers.setter
    def action_servers(self, value: list[rosgraph_msgs.msg.Action]) -> None: ...
