# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

import geometry_msgs.msg

class Inertia:
    def __init__(
        self,
        *,
        m: float = ...,
        com: geometry_msgs.msg.Vector3 = ...,
        ixx: float = ...,
        ixy: float = ...,
        ixz: float = ...,
        iyy: float = ...,
        iyz: float = ...,
        izz: float = ...,
        check_fields: bool = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def m(self) -> float: ...
    @m.setter
    def m(self, value: float) -> None: ...
    @property
    def com(self) -> geometry_msgs.msg.Vector3: ...
    @com.setter
    def com(self, value: geometry_msgs.msg.Vector3) -> None: ...
    @property
    def ixx(self) -> float: ...
    @ixx.setter
    def ixx(self, value: float) -> None: ...
    @property
    def ixy(self) -> float: ...
    @ixy.setter
    def ixy(self, value: float) -> None: ...
    @property
    def ixz(self) -> float: ...
    @ixz.setter
    def ixz(self, value: float) -> None: ...
    @property
    def iyy(self) -> float: ...
    @iyy.setter
    def iyy(self, value: float) -> None: ...
    @property
    def iyz(self) -> float: ...
    @iyz.setter
    def iyz(self, value: float) -> None: ...
    @property
    def izz(self) -> float: ...
    @izz.setter
    def izz(self, value: float) -> None: ...
