# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

import sensor_msgs.msg
import std_msgs.msg

class DisparityImage:
    def __init__(
        self,
        *,
        header: std_msgs.msg.Header = ...,
        image: sensor_msgs.msg.Image = ...,
        f: float = ...,
        t: float = ...,
        valid_window: sensor_msgs.msg.RegionOfInterest = ...,
        min_disparity: float = ...,
        max_disparity: float = ...,
        delta_d: float = ...,
        check_fields: bool = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def header(self) -> std_msgs.msg.Header: ...
    @header.setter
    def header(self, value: std_msgs.msg.Header) -> None: ...
    @property
    def image(self) -> sensor_msgs.msg.Image: ...
    @image.setter
    def image(self, value: sensor_msgs.msg.Image) -> None: ...
    @property
    def f(self) -> float: ...
    @f.setter
    def f(self, value: float) -> None: ...
    @property
    def t(self) -> float: ...
    @t.setter
    def t(self, value: float) -> None: ...
    @property
    def valid_window(self) -> sensor_msgs.msg.RegionOfInterest: ...
    @valid_window.setter
    def valid_window(self, value: sensor_msgs.msg.RegionOfInterest) -> None: ...
    @property
    def min_disparity(self) -> float: ...
    @min_disparity.setter
    def min_disparity(self, value: float) -> None: ...
    @property
    def max_disparity(self) -> float: ...
    @max_disparity.setter
    def max_disparity(self, value: float) -> None: ...
    @property
    def delta_d(self) -> float: ...
    @delta_d.setter
    def delta_d(self, value: float) -> None: ...
