# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

import std_msgs.msg

class OccupancyGridUpdate:
    def __init__(
        self,
        *,
        header: std_msgs.msg.Header = ...,
        x: int = ...,
        y: int = ...,
        width: int = ...,
        height: int = ...,
        data: list[int] = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def header(self) -> std_msgs.msg.Header: ...
    @header.setter
    def header(self, value: std_msgs.msg.Header) -> None: ...
    @property
    def x(self) -> int: ...
    @x.setter
    def x(self, value: int) -> None: ...
    @property
    def y(self) -> int: ...
    @y.setter
    def y(self, value: int) -> None: ...
    @property
    def width(self) -> int: ...
    @width.setter
    def width(self, value: int) -> None: ...
    @property
    def height(self) -> int: ...
    @height.setter
    def height(self, value: int) -> None: ...
    @property
    def data(self) -> list[int]: ...
    @data.setter
    def data(self, value: list[int]) -> None: ...
