# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

class ProjectedMapInfo:
    def __init__(
        self,
        *,
        frame_id: str = ...,
        x: float = ...,
        y: float = ...,
        width: float = ...,
        height: float = ...,
        min_z: float = ...,
        max_z: float = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def frame_id(self) -> str: ...
    @frame_id.setter
    def frame_id(self, value: str) -> None: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, value: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, value: float) -> None: ...
    @property
    def width(self) -> float: ...
    @width.setter
    def width(self, value: float) -> None: ...
    @property
    def height(self) -> float: ...
    @height.setter
    def height(self, value: float) -> None: ...
    @property
    def min_z(self) -> float: ...
    @min_z.setter
    def min_z(self, value: float) -> None: ...
    @property
    def max_z(self) -> float: ...
    @max_z.setter
    def max_z(self, value: float) -> None: ...
