# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

import sensor_msgs.msg
import std_msgs.msg

class CameraInfo:
    def __init__(
        self,
        *,
        header: std_msgs.msg.Header = ...,
        height: int = ...,
        width: int = ...,
        distortion_model: str = ...,
        d: list[float] = ...,
        k: list[float] = ...,
        r: list[float] = ...,
        p: list[float] = ...,
        binning_x: int = ...,
        binning_y: int = ...,
        roi: sensor_msgs.msg.RegionOfInterest = ...,
        check_fields: bool = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def header(self) -> std_msgs.msg.Header: ...
    @header.setter
    def header(self, value: std_msgs.msg.Header) -> None: ...
    @property
    def height(self) -> int: ...
    @height.setter
    def height(self, value: int) -> None: ...
    @property
    def width(self) -> int: ...
    @width.setter
    def width(self, value: int) -> None: ...
    @property
    def distortion_model(self) -> str: ...
    @distortion_model.setter
    def distortion_model(self, value: str) -> None: ...
    @property
    def d(self) -> list[float]: ...
    @d.setter
    def d(self, value: list[float]) -> None: ...
    @property
    def k(self) -> list[float]: ...
    @k.setter
    def k(self, value: list[float]) -> None: ...
    @property
    def r(self) -> list[float]: ...
    @r.setter
    def r(self, value: list[float]) -> None: ...
    @property
    def p(self) -> list[float]: ...
    @p.setter
    def p(self, value: list[float]) -> None: ...
    @property
    def binning_x(self) -> int: ...
    @binning_x.setter
    def binning_x(self, value: int) -> None: ...
    @property
    def binning_y(self) -> int: ...
    @binning_y.setter
    def binning_y(self, value: int) -> None: ...
    @property
    def roi(self) -> sensor_msgs.msg.RegionOfInterest: ...
    @roi.setter
    def roi(self, value: sensor_msgs.msg.RegionOfInterest) -> None: ...
