# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

import geometry_msgs.msg
import std_msgs.msg

class Imu:
    def __init__(
        self,
        *,
        header: std_msgs.msg.Header = ...,
        orientation: geometry_msgs.msg.Quaternion = ...,
        orientation_covariance: list[float] = ...,
        angular_velocity: geometry_msgs.msg.Vector3 = ...,
        angular_velocity_covariance: list[float] = ...,
        linear_acceleration: geometry_msgs.msg.Vector3 = ...,
        linear_acceleration_covariance: list[float] = ...,
        check_fields: bool = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def header(self) -> std_msgs.msg.Header: ...
    @header.setter
    def header(self, value: std_msgs.msg.Header) -> None: ...
    @property
    def orientation(self) -> geometry_msgs.msg.Quaternion: ...
    @orientation.setter
    def orientation(self, value: geometry_msgs.msg.Quaternion) -> None: ...
    @property
    def orientation_covariance(self) -> list[float]: ...
    @orientation_covariance.setter
    def orientation_covariance(self, value: list[float]) -> None: ...
    @property
    def angular_velocity(self) -> geometry_msgs.msg.Vector3: ...
    @angular_velocity.setter
    def angular_velocity(self, value: geometry_msgs.msg.Vector3) -> None: ...
    @property
    def angular_velocity_covariance(self) -> list[float]: ...
    @angular_velocity_covariance.setter
    def angular_velocity_covariance(self, value: list[float]) -> None: ...
    @property
    def linear_acceleration(self) -> geometry_msgs.msg.Vector3: ...
    @linear_acceleration.setter
    def linear_acceleration(self, value: geometry_msgs.msg.Vector3) -> None: ...
    @property
    def linear_acceleration_covariance(self) -> list[float]: ...
    @linear_acceleration_covariance.setter
    def linear_acceleration_covariance(self, value: list[float]) -> None: ...
