# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

import sensor_msgs.msg
import std_msgs.msg

class MultiEchoLaserScan:
    def __init__(
        self,
        *,
        header: std_msgs.msg.Header = ...,
        angle_min: float = ...,
        angle_max: float = ...,
        angle_increment: float = ...,
        time_increment: float = ...,
        scan_time: float = ...,
        range_min: float = ...,
        range_max: float = ...,
        ranges: list[sensor_msgs.msg.LaserEcho] = ...,
        intensities: list[sensor_msgs.msg.LaserEcho] = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def header(self) -> std_msgs.msg.Header: ...
    @header.setter
    def header(self, value: std_msgs.msg.Header) -> None: ...
    @property
    def angle_min(self) -> float: ...
    @angle_min.setter
    def angle_min(self, value: float) -> None: ...
    @property
    def angle_max(self) -> float: ...
    @angle_max.setter
    def angle_max(self, value: float) -> None: ...
    @property
    def angle_increment(self) -> float: ...
    @angle_increment.setter
    def angle_increment(self, value: float) -> None: ...
    @property
    def time_increment(self) -> float: ...
    @time_increment.setter
    def time_increment(self, value: float) -> None: ...
    @property
    def scan_time(self) -> float: ...
    @scan_time.setter
    def scan_time(self, value: float) -> None: ...
    @property
    def range_min(self) -> float: ...
    @range_min.setter
    def range_min(self, value: float) -> None: ...
    @property
    def range_max(self) -> float: ...
    @range_max.setter
    def range_max(self, value: float) -> None: ...
    @property
    def ranges(self) -> list[sensor_msgs.msg.LaserEcho]: ...
    @ranges.setter
    def ranges(self, value: list[sensor_msgs.msg.LaserEcho]) -> None: ...
    @property
    def intensities(self) -> list[sensor_msgs.msg.LaserEcho]: ...
    @intensities.setter
    def intensities(self, value: list[sensor_msgs.msg.LaserEcho]) -> None: ...
