# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

import sensor_msgs.msg
import std_msgs.msg

class PointCloud2:
    def __init__(
        self,
        *,
        header: std_msgs.msg.Header = ...,
        height: int = ...,
        width: int = ...,
        fields: list[sensor_msgs.msg.PointField] = ...,
        is_bigendian: bool = ...,
        point_step: int = ...,
        row_step: int = ...,
        data: list[int] = ...,
        is_dense: bool = ...,
        check_fields: bool = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def header(self) -> std_msgs.msg.Header: ...
    @header.setter
    def header(self, value: std_msgs.msg.Header) -> None: ...
    @property
    def height(self) -> int: ...
    @height.setter
    def height(self, value: int) -> None: ...
    @property
    def width(self) -> int: ...
    @width.setter
    def width(self, value: int) -> None: ...
    @property
    def fields(self) -> list[sensor_msgs.msg.PointField]: ...
    @fields.setter
    def fields(self, value: list[sensor_msgs.msg.PointField]) -> None: ...
    @property
    def is_bigendian(self) -> bool: ...
    @is_bigendian.setter
    def is_bigendian(self, value: bool) -> None: ...
    @property
    def point_step(self) -> int: ...
    @point_step.setter
    def point_step(self, value: int) -> None: ...
    @property
    def row_step(self) -> int: ...
    @row_step.setter
    def row_step(self, value: int) -> None: ...
    @property
    def data(self) -> list[int]: ...
    @data.setter
    def data(self, value: list[int]) -> None: ...
    @property
    def is_dense(self) -> bool: ...
    @is_dense.setter
    def is_dense(self, value: bool) -> None: ...
