# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

class RegionOfInterest:
    def __init__(
        self,
        *,
        x_offset: int = ...,
        y_offset: int = ...,
        height: int = ...,
        width: int = ...,
        do_rectify: bool = ...,
        check_fields: bool = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def x_offset(self) -> int: ...
    @x_offset.setter
    def x_offset(self, value: int) -> None: ...
    @property
    def y_offset(self) -> int: ...
    @y_offset.setter
    def y_offset(self, value: int) -> None: ...
    @property
    def height(self) -> int: ...
    @height.setter
    def height(self, value: int) -> None: ...
    @property
    def width(self) -> int: ...
    @width.setter
    def width(self, value: int) -> None: ...
    @property
    def do_rectify(self) -> bool: ...
    @do_rectify.setter
    def do_rectify(self, value: bool) -> None: ...
