# This file was generated automatically by
# `scripts/generate_stubs.py`.
# Do not modify it manually. If needed re-run the script.

import builtin_interfaces.msg
import geometry_msgs.msg
import std_msgs.msg

class ImageMarker:
    # Constants
    CIRCLE: int = 0
    LINE_STRIP: int = 1
    LINE_LIST: int = 2
    POLYGON: int = 3
    POINTS: int = 4
    ADD: int = 0
    REMOVE: int = 1

    def __init__(
        self,
        *,
        header: std_msgs.msg.Header = ...,
        ns: str = ...,
        id: int = ...,  # noqa: A002
        type: int = ...,  # noqa: A002
        action: int = ...,
        position: geometry_msgs.msg.Point = ...,
        scale: float = ...,
        outline_color: std_msgs.msg.ColorRGBA = ...,
        filled: int = ...,
        fill_color: std_msgs.msg.ColorRGBA = ...,
        lifetime: builtin_interfaces.msg.Duration = ...,
        points: list[geometry_msgs.msg.Point] = ...,
        outline_colors: list[std_msgs.msg.ColorRGBA] = ...,
        check_fields: bool = ...,
    ) -> None: ...
    @classmethod
    def get_fields_and_field_types(cls) -> dict[str, str]: ...

    # Members
    @property
    def header(self) -> std_msgs.msg.Header: ...
    @header.setter
    def header(self, value: std_msgs.msg.Header) -> None: ...
    @property
    def ns(self) -> str: ...
    @ns.setter
    def ns(self, value: str) -> None: ...
    @property
    def id(self) -> int: ...
    @id.setter
    def id(self, value: int) -> None: ...
    @property
    def type(self) -> int: ...
    @type.setter
    def type(self, value: int) -> None: ...
    @property
    def action(self) -> int: ...
    @action.setter
    def action(self, value: int) -> None: ...
    @property
    def position(self) -> geometry_msgs.msg.Point: ...
    @position.setter
    def position(self, value: geometry_msgs.msg.Point) -> None: ...
    @property
    def scale(self) -> float: ...
    @scale.setter
    def scale(self, value: float) -> None: ...
    @property
    def outline_color(self) -> std_msgs.msg.ColorRGBA: ...
    @outline_color.setter
    def outline_color(self, value: std_msgs.msg.ColorRGBA) -> None: ...
    @property
    def filled(self) -> int: ...
    @filled.setter
    def filled(self, value: int) -> None: ...
    @property
    def fill_color(self) -> std_msgs.msg.ColorRGBA: ...
    @fill_color.setter
    def fill_color(self, value: std_msgs.msg.ColorRGBA) -> None: ...
    @property
    def lifetime(self) -> builtin_interfaces.msg.Duration: ...
    @lifetime.setter
    def lifetime(self, value: builtin_interfaces.msg.Duration) -> None: ...
    @property
    def points(self) -> list[geometry_msgs.msg.Point]: ...
    @points.setter
    def points(self, value: list[geometry_msgs.msg.Point]) -> None: ...
    @property
    def outline_colors(self) -> list[std_msgs.msg.ColorRGBA]: ...
    @outline_colors.setter
    def outline_colors(self, value: list[std_msgs.msg.ColorRGBA]) -> None: ...
